### ISSUE TITLE
An extra scroll bar is displayed

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-inspector#1]
I tried using Grimoire.js Inspector, but it seems that there are many scroll bars displayed.
![image](https://cloud.githubusercontent.com/assets/1833979/26529264/e35643a4-43f7-11e7-9b71-78ee02361d23.png)
I think this is a matter of CSS. Adding the following code seems to display correctly.
https://github.com/GrimoireGL/grimoirejs-inspector/blob/master/src/devtool/init/init.css#L42-L47
```css
body,html{
  margin:0px;
  padding:0px;
  height:100%;
  overflow: hidden; /* Add */
  background-color: #232523;
}
```
![image](https://cloud.githubusercontent.com/assets/1833979/26529284/3b5f327c-43f8-11e7-91a9-538e0b9485d4.png)
